"""add columns to table

Revision ID: 511dc34b33c1
Revises: 8a97bc463457
Create Date: 2025-07-03 07:23:02.913087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511dc34b33c1'
down_revision = '8a97bc463457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
